### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__C)

### ISSUE THREAD

**Issue by hszhoushen** [ChCh1999/RTPB#4]
# Enviroment problem 
* Using torch1.6 or higher version (including 1.8, 1.10, 1.11), there is one compiling error that occurred

(rtpb) root@kemove-SYS-4029GP-TRT:~/RTPB# python setup.py build develop
running build
running build_py
running build_ext
building 'maskrcnn_benchmark._C' extension
Emitting ninja build file /root/RTPB/build/temp.linux-x86_64-3.7/build.ninja...
Traceback (most recent call last):
  File "setup.py", line 68, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/gpp/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gpp/miniconda3/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/gpp/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/gpp/miniconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1351, in _write_ninja_file_and_compile_objects
    with_cuda=with_cuda)
  File "/home/gpp/miniconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1874, in _write_ninja_file
    assert len(sources) > 0
AssertionError

* Using torch1.5 or lower, successfully compiled, but when using the training script, the following error is encountered

RTPB/maskrcnn_benchmark/layers/nms.py", line 3, in <module>
    from maskrcnn_benchmark import _C
ImportError: dynamic module does not define module export function (PyInit__C)

Could you please list the detailed environment that you were using?

**Comment by ChCh1999** [comment]
Here is my environment with GeForce RTX 3090 and  CUDA 11.2.
```
name: SGG
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h3811e60_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py39hf3d152e_0
  - cffi=1.14.6=py39h4bc2ebd_1
  - chardet=4.0.0=py39hf3d152e_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - cmake=3.21.2=h8897547_0
  - cryptography=3.4.7=py39hbca0aa6_0
  - cudatoolkit=11.2.2=he111cf0_8
  - dataclasses=0.8=pyhc8e2a94_3
  - decorator=5.1.0=pyhd8ed1ab_0
  - expat=2.4.1=h9c3ff4c_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py39hf3d152e_3
  - h5py=3.4.0=nompi_py39h7e08c79_101
  - hdf5=1.12.1=nompi_h2750804_100
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipython=7.28.0=py39hef51801_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py39hf3d152e_2
  - jpeg=9d=h36c2ea0_0
  - krb5=1.19.2=hcc1bbae_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_mkl
  - libcblas=3.9.0=11_linux64_mkl
  - libcurl=7.79.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h9c3ff4c_1
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgfortran-ng=11.2.0=h69a702a_8
  - libgfortran5=11.2.0=h5c6108e_8
  - libgomp=11.2.0=h1d223b6_8
  - liblapack=3.9.0=11_linux64_mkl
  - libnghttp2=1.43.0=h812cca2_0
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.16.0=h780b84a_0
  - libssh2=1.10.0=ha56f1ee_0
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - libtiff=4.3.0=hf544144_1
  - libuv=1.42.0=h7f98852_0
  - libwebp-base=1.2.1=h7f98852_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-include=2021.3.0=h726a3e6_557
  - ncurses=6.2=h58526e2_4
  - numpy=1.21.2=py39hdbf815f_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py39ha612740_0
  - pip=21.2.4=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py39hf3d152e_3
  - python=3.9.7=hb7a2778_1_cpython
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=cpu_py39h818de69_2
  - pyyaml=5.4.1=py39h3811e60_1
  - readline=8.1=h46c0cb4_0
  - rhash=1.4.1=h7f98852_0
  - scipy=1.7.1=py39hee8e79c_0
  - setuptools=58.0.4=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h7f98852_1
  - sqlite=3.36.0=h9cd32fc_1
  - tk=8.6.11=h27826a3_1
  - torchaudio=0.9.0=py39
  - torchvision=0.2.2=py_3
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - apex==0.1
    - beautifulsoup4==4.7.1
    - beautifultable==0.7.0
    - boto3==1.19.5
    - botocore==1.22.5
    - click==6.7
    - cycler==0.10.0
    - cython==0.29.24
    - docker==3.6.0
    - docker-pycreds==0.4.0
    - evalai==1.3.14
    - idna==2.10
    - jmespath==0.10.0
    - kiwisolver==1.3.2
    - lxml==4.6.2
    - matplotlib==3.4.3
    - ninja==1.10.2.2
    - opencv-python==4.5.3.56
    - overrides==6.1.0
    - pycocotools==2.0
    - pyparsing==2.4.7
    - python-dateutil==2.7.3
    - requests==2.25.1
    - s3transfer==0.5.0
    - soupsieve==2.2.1
    - termcolor==1.1.0
    - tqdm==4.62.3
    - typing-utils==0.1.0
    - validators==0.12.6
    - websocket-client==1.2.1
    - yacs==0.1.8

```

**Comment by ChCh1999** [comment]
There is a bug in `setup.py`, I just fixed it.

**Comment by hszhoushen** [comment]
> There is a bug in `setup.py`, I just fixed it.

Thanks for your rapid response, it really helps a lot. problem solved!!! The bug was all about setup.py.

**Comment by duang33** [comment]
> There is a bug in `setup.py`, I just fixed it.

how to fix?
